name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync-code:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync code and tags to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/diaochangpeng/db-designer.git
          git push gitee dev:master --force
          git push gitee --tags --force